[WIP] Feature/upgradable_contract
plexus-money/contracts pull request #23
Opened 2021-06-11 07:31 UTC by softskillpro

[WIP] Upgradable contract

2021-06-15 19:22 UTC, terminator0x commented
@softskillpro is this PR ready for review?

2021-06-15 19:42 UTC, softskillpro commented
> @softskillpro is this PR ready for review?
Yes. I fixed conflicts and pushed it. it works on my local properly.   
But currently I see following issues with github action. 
"An unexpected error occurred:
ProviderError: Must be authenticated!"
it looks like hadhat config issue - RPC_NODE_URL

2021-06-16 08:23 UTC, terminator0x commented
> > @softskillpro is this PR ready for review?
> 
> Yes. I fixed conflicts and pushed. it works on my local properly.
> But currently, I see the following issue with GitHub action.
> "An unexpected error occurred: ProviderError: Must be authenticated!"
> It looks like hardhat config issue - RPC_NODE_URL

Pleas rebase against the master branch, so that you get the updated github actions file and the tests will start working.

2021-06-16 15:14 UTC, terminator0x requested changes
@softskillpro Great work, so far, I love it 😃 . But still their are a few things that need to be sorted.

1.  Please import the `Ownable` contracts from the `@openzeppelin` node.js lib 
   i.e. for the `Ownable.sol` file you do the following

```sol
import "@openzeppelin/contracts/access/Ownable.sol";
```
- The reason for this is because openzeppelin contracts are trusted and hence it makes auditing our contracts a much easier task.

2. Add more tests to verify that the ownership of the deployed contracts belongs to the respective proxy with each new upgrade, this is crucial because a compromise would upet the whole plexus eco-system.
3. Add a test to check that the ownership of the proxy contracts remains to be the original deployer account and this shouldn't change at all regardless of how many upgrades are done.
4. Finally add another test to verify that the global state variables for the `tokenrewards.sol` contract will always remain the same regardless of how many times the contract is deployed.
i.e. the `stakingTokenWhitelist`, `stakingTokensAddress`, `stakingLPTokensAddress` and the rest of the global public vars should remain the same in the proxy contract after 3 deployments of the same contract in different addresses
3.

2021-06-16 19:33 UTC, softskillpro commented
> @softskillpro Great work, so far, I love it 😃 . But still their are a few things that need to be sorted.
> 
> 1. Please import the `Ownable` contracts from the `@openzeppelin` node.js lib
>    i.e. for the `Ownable.sol` file you do the following
> 
> ```gerber
> import "@openzeppelin/contracts/access/Ownable.sol";
> ```
> 
> * The reason for this is because openzeppelin contracts are trusted and hence it makes auditing our contracts a much easier task.
> 
> 1. Add more tests to verify that the ownership of the deployed contracts belongs to the respective proxy with each new upgrade, this is crucial because a compromise would lead to loss of funds for the whole plexus eco-system.
> 2. Add a test to check that the ownership of the proxy contracts remains to be the original deployer account and this shouldn't change at all regardless of how many upgrades are done.
> 3. Finally add another test to verify that the global state variables for the `tokenrewards.sol` contract will always remain the same regardless of how many times the contract is deployed.
>    i.e. the `stakingTokenWhitelist`, `stakingTokensAddress`, `stakingLPTokensAddress` and the rest of the global public vars should remain the same in the proxy contract after 3 deployments of the same contract in different addresses

2021-06-16 19:48 UTC, softskillpro commented
@terminator0x 
1. Please import the Ownable contracts from the @openzeppelin node.js lib
import "@openzeppelin/contracts/access/Ownable.sol";

Ownable.sol of openzeppelin doesn't have functions for updating owner, as our contracts need to this feature.
Most of the contracts has changeOwner() functions.
So we need to customize @openzeppelin/contracts/access/Ownable.sol for using in our contracts.
I'll copy the source and add a new function that update owner, Is it okay?
for example, function updateOwner(address newOwner) public onlyOwner {}

2021-06-16 19:49 UTC, softskillpro commented
@terminator0x Ownable.sol of openzeppelin doesn't have functions for updating owner, as our contracts need to this feature.
Most of the contracts has changeOwner() functions.
So we need to customize @openzeppelin/contracts/access/Ownable.sol for using in our contracts.
I'll copy the source and add a new function that update owner, Is it okay?
for example, function updateOwner(address newOwner) public onlyOwner {}

2021-06-16 19:49 UTC, softskillpro commented
> > @softskillpro Great work, so far, I love it 😃 . But still their are a few things that need to be sorted.
> > 
> > 1. Please import the `Ownable` contracts from the `@openzeppelin` node.js lib
> >    i.e. for the `Ownable.sol` file you do the following
> > 
> > ```
> > import "@openzeppelin/contracts/access/Ownable.sol";
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * The reason for this is because openzeppelin contracts are trusted and hence it makes auditing our contracts a much easier task.
> > 
> > 
> > 1. Add more tests to verify that the ownership of the deployed contracts belongs to the respective proxy with each new upgrade, this is crucial because a compromise would lead to loss of funds for the whole plexus eco-system.
> > 2. Add a test to check that the ownership of the proxy contracts remains to be the original deployer account and this shouldn't change at all regardless of how many upgrades are done.
> > 3. Finally add another test to verify that the global state variables for the `tokenrewards.sol` contract will always remain the same regardless of how many times the contract is deployed.
> >    i.e. the `stakingTokenWhitelist`, `stakingTokensAddress`, `stakingLPTokensAddress` and the rest of the global public vars should remain the same in the proxy contract after 3 deployments of the same contract in different addresses

@terminator0x Ownable.sol of openzeppelin doesn't have functions for updating owner, as our contracts need to this feature.
Most of the contracts has changeOwner() functions.
So we need to customize @openzeppelin/contracts/access/Ownable.sol for using in our contracts.
I'll copy the source and add a new function that update owner, Is it okay?
for example, function updateOwner(address newOwner) public onlyOwner {}

2021-06-17 09:38 UTC, terminator0x requested changes

2021-06-17 09:38 UTC, terminator0x commented on test/8_proxy.js
> +    describe('', () => {
Remove the describe section, it's unnecessary

2021-06-17 09:38 UTC, terminator0x commented on test/8_proxy.js
> +    describe('', () => {
Remove the describe function here

2021-06-17 09:38 UTC, terminator0x commented on test/8_proxy.js
> +    describe('', () => {
Same here remove the empty describe section, this should only be used to literally describe a testing section, so we can't have it blank

2021-06-17 09:38 UTC, terminator0x commented on test/8_proxy.js
> +    describe('', () => {
Same here remove empty describe section and leave the it function

2021-06-17 09:38 UTC, terminator0x commented on test/8_proxy.js
> +    describe('', () => {
Same here remove empty describe section and leave the it function

2021-06-17 09:38 UTC, terminator0x commented on test/8_proxy.js
> +    describe('', () => {
Same here remove empty describe section and leave the it function

2021-06-17 09:38 UTC, terminator0x commented on contracts/proxyLib/Context.sol
> +// SPDX-License-Identifier: MIT
Import this file from the openzeppelin node.js lib

2021-06-17 22:17 UTC, terminator0x commented
Rebased into #29

2021-06-17 22:17 UTC, closed without merging